### ISSUE TITLE
Rename repo to OpenSamples

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/OpenSamples#1]
By transfering this repo to ReadAlongs, I lost admin privileges to it!

@roedoejet : 
 - please rename to OpenSamples
 - please grant us, the core RAS team, admin privileges to the ReadAlongs account (if you're OK with that).

**Comment by roedoejet** [comment]
Of course! I think the default when you accept the invitation is to just become a member. I just changed it so you should be an owner/admin new. One of us will have to do that for @littell and @dhdaines too when they join.
